### ISSUE TITLE
Add comments to the AST?

### ISSUE THREAD

**Issue by phated** [creditkarma/thrift-parser#16]
Can we add the comments to the AST?  I think the Thrift binary actually does something with them but we currently don't because the other parser didn't include them in the output.

**Comment by kevinbgreene** [comment]
Added in #29 

@phated I merged the change for having comment blocks be array of strings. My thought is it will give more control in the codegen. I'm not feeling solid either way though. We can revert. Just need these other changes for the codegen to consume.
