### ISSUE TITLE
We need to handle i64 as a value for const and fields.

### ISSUE THREAD

**Issue by kevinbgreene** [creditkarma/thrift-parser#33]
Right now all numeric values are being parsed using parseInt or parseFloat. We should construct Int64 as the value for i64 fields. We're not handling default values in Scrooge at the moment, but this needs to be fixed.

**Comment by phated** [comment]
@kevinbgreene this was discussed previously and decided that numbers should be parsed as strings to avoid using Int64. Ref https://github.com/creditkarma/thrift-parser-fork/issues/5

**Comment by jessezhang91** [comment]
I have changed the type of `IntConstant.value` from `number` to `string` and move the `parseInt` into the `thrift-typescript` library.

In the `thrift-typescript` library, I've wrapped all references to `IntConstant.value` with `parseInt` except for the `renderValue` `SyntaxType.I64Keyword` case.

If this sounds like a reasonable solution, I'll commit the changes and open the PRs.

**Comment by kevin-greene-ck** [comment]
@jessezhang91 Yeah, that's certainly a reasonable solution.

My other thought, and why I haven't acted on this yet, was to change the type of IntConstant and DoubleConstant to something like:
```
interface IntConstant extends SyntaxNode {
  type: SyntaxType.IntConstant
  value: IntegerLiteral | HexLiteral
}

interface DoubleConstant extends SyntaxNode {
  type: SyntaxType.DoubleConstant
  value: FloatLiteral | ExponentialLiteral
}
```
This is the more complex solution, but it keeps the AST more consistent.

Anyway, please go a head and submit your PRs.

**Comment by jessezhang91** [comment]
Cool, I've opened up the PRs. I can come back and implement your solution in the near future. It's definitely the better approach.

**Comment by kevin-greene-ck** [comment]
Fixed: https://github.com/creditkarma/thrift-parser/commit/53d26275e0532ad46db05249335e696842efc60c
