### ISSUE TITLE
Doesn't parse "complex.thrift"

### ISSUE THREAD

**Issue by phated** [creditkarma/thrift-parser#5]
I just tried to parse https://github.com/creditkarma/thrift-typescript/blob/master/fixtures/complex.thrift in the ASTExplorer and it fails.  Not sure what part it is failing on.

**Comment by kevinbgreene** [comment]
@phated Question, in complex.thrift you have this
```
struct WithContainers {
    1: map<string, string> map
}
```
Do you know of an example of this being supported? An identifier using a keyword as its value? I searched through all the apache tests and don't see them testing for it. I guess by the language definition it's allowed. The Scrooge code generator does not allow this. I'm inclined to forbid it. We're not using this internally as Scrooge doesn't allow keywords to be used as identifiers.

Other than that, this is parsing complex.thrift now.

**Comment by phated** [comment]
@kevinbgreene I don't actually know if I ran that through the thrift binary.  I think it's fine to forbid it.
