### ISSUE TITLE
Doesn't parse custom namespace scopes

### ISSUE THREAD

**Issue by phated** [creditkarma/thrift-parser#9]
Tried to parse:
```thrift
namespace js.ts MyThing
```
And it fails.  It succeeds with `js` instead of `js.ts`

**Comment by kevinbgreene** [comment]
Is this supported? It's not supported in the IDL nor the missing guide that is referenced everywhere. Is this a decision we made?

**Comment by phated** [comment]
Yes, this is something the Thrift binary supports (I believe it shows a warning during code-gen).  Further discussion at https://github.com/creditkarma/thrift-parser-fork/issues/14 and https://github.com/creditkarma/thrift-typescript/issues/15

**Comment by kevinbgreene** [comment]
Ah, thanks for the context. I'm building entirely off of the grammar defined in the idl docs.
